### ISSUE TITLE
Adding content for day 9

### ISSUE THREAD

**Issue by sidharth2829** [subhadipbhowmik/30-Days-Of-CPP#66]
### Select the Day of Content

Day 9

### What information is missing?

I want to add content regarding operation on arrays and strings for day 9.

**Comment by subhadipbhowmik** [comment]
You are requested to work upon any of 1-7 days. Because we have given instruction along with image assets.. Ful fill those content firts.

<img width="959" alt="Screenshot 2024-05-30 104016" src="https://github.com/subhadipbhowmik/30-Days-Of-CPP/assets/57017965/4f2a5cbb-1b67-4dcf-be9e-985f1adc1715">
